version: '3'
services:
  myapp:
    build: image
    image: kebab-task-name
    container_name: snake_task_name
    hostname: snake_task_name
    environment:
      APP_MESSAGE: '${MESSAGE:-Hello, world!}'
      APP_PORT: '${CONTAINER_PORT:-8080}'
    ports:
    - ${HOST_PORT:-8080}:${CONTAINER_PORT:-8080}
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:${APP_PORT:-8080}/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 30