version: '3'
services:
  snake_app_name:
    build: src
    image: ${IMAGE:-kebab-app-name}
    container_name: snake_app_name
    hostname: snake_app_name
    env_file: 'src/template.env'
    environment:
      APP_PORT: ${APP_PORT:-8080}
    ports:
    - "${HOST_PORT:-8080}:${APP_PORT:-8080}"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:${APP_PORT:-8080}/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 30